
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Agancy
{

    public int Id { get; set; }

    public string NameSherkatForushgah { get; set; }

    public string NameModiramelMasool { get; set; }

    public string Email { get; set; }

    public Nullable<int> Ostan { get; set; }

    public Nullable<int> Shahrestan { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string Tel { get; set; }

    public string Fax { get; set; }

    public string RegisterDate { get; set; }

    public string RegisterPlace { get; set; }

    public string JavazOrAsasnameh { get; set; }

    public string TedadPersonnelFanni { get; set; }

    public string TedadPersonnelEdari { get; set; }

    public string TedadPersonnelForush { get; set; }

    public string ProjeAnjamDadeid { get; set; }

    public string NamayandegBrandDashte { get; set; }

    public string TavanayiSaliane { get; set; }

    public string AshnayiBaPrada { get; set; }

    public Nullable<int> EjareShakhsi { get; set; }

    public Nullable<bool> SanadMelki { get; set; }

    public Nullable<bool> Safte { get; set; }

    public Nullable<bool> CheckeZemanat { get; set; }

    public Nullable<bool> ZemanatNamehBanki { get; set; }

    public Nullable<bool> VajhNaghd { get; set; }

    public string PrintGardesh { get; set; }

    public Nullable<System.DateTime> TarikheSabteDarkhast { get; set; }

}

}
