
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class BrandCategory
{

    public BrandCategory()
    {

        this.Products = new HashSet<Product>();

    }


    public int Id { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> BrandId { get; set; }



    public virtual Category Category { get; set; }

    public virtual ICollection<Product> Products { get; set; }

    public virtual Brand Brand { get; set; }

}

}
