
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Career
{

    public long Id { get; set; }

    public string Name { get; set; }

    public string LastName { get; set; }

    public string CodeMelli { get; set; }

    public string ResumeFilePath { get; set; }

}

}
