

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatisEntities : DbContext
{
    public DatisEntities()
        : base("name=DatisEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BrandCategory> BrandCategories { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Feature> Features { get; set; }

    public virtual DbSet<FeatureProduct> FeatureProducts { get; set; }

    public virtual DbSet<File> Files { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<CategoryChildren> CategoryChildrens { get; set; }

    public virtual DbSet<ClientsMessage> ClientsMessages { get; set; }

    public virtual DbSet<TermsOfGarranty> TermsOfGarranties { get; set; }

    public virtual DbSet<Repair> Repairs { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<Career> Careers { get; set; }

    public virtual DbSet<Agancy> Agancies { get; set; }

    public virtual DbSet<Solution> Solutions { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<SerialNumber> SerialNumbers { get; set; }

    public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }

    public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }

    public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }

    public virtual DbSet<SiteContent> SiteContents { get; set; }

    public virtual DbSet<FileManagerFile> FileManagerFiles { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectOrder> ProjectOrders { get; set; }

}

}

