
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class FeatureProduct
{

    public int Id { get; set; }

    public Nullable<int> ProductId { get; set; }

    public Nullable<int> FeatureId { get; set; }

    public string Value { get; set; }



    public virtual Feature Feature { get; set; }

    public virtual Product Product { get; set; }

}

}
