
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Feature
{

    public Feature()
    {

        this.FeatureProducts = new HashSet<FeatureProduct>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> CategoryId { get; set; }



    public virtual Category Category { get; set; }

    public virtual ICollection<FeatureProduct> FeatureProducts { get; set; }

}

}
