
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class File
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Path { get; set; }

    public Nullable<int> Type { get; set; }

    public Nullable<int> TableId { get; set; }

    public Nullable<int> ForeignId { get; set; }

    public string Extension { get; set; }

    public string ServerName { get; set; }

}

}
