
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public Product()
    {

        this.FeatureProducts = new HashSet<FeatureProduct>();

    }


    public int Id { get; set; }

    public string Model { get; set; }

    public Nullable<int> BrandCategoryId { get; set; }

    public string FeaturesSummary { get; set; }

    public string Description { get; set; }

    public string Summary { get; set; }



    public virtual BrandCategory BrandCategory { get; set; }

    public virtual ICollection<FeatureProduct> FeatureProducts { get; set; }

}

}
