
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectOrder
{

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> OrderId { get; set; }

    public int Id { get; set; }

}

}
