
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public int Id { get; set; }

    public string NameSherkatForushgah { get; set; }

    public string NameModiramelMasool { get; set; }

    public string Email { get; set; }

    public Nullable<int> Ostan { get; set; }

    public Nullable<int> Shahrestan { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string Tel { get; set; }

    public string TarikheSabteProject { get; set; }

    public string TarikheTakhmineEjra { get; set; }

    public string ProjectName { get; set; }

    public string OstaneProject { get; set; }

    public string ShahreProject { get; set; }

    public string AddressProject { get; set; }

    public Nullable<bool> MohandesiGhablAzForush { get; set; }

    public Nullable<bool> Ejra { get; set; }

    public Nullable<bool> NaghsheKeshi { get; set; }

    public Nullable<bool> MoshavereProject { get; set; }

    public Nullable<bool> Janamayi { get; set; }

    public Nullable<bool> Nezarat { get; set; }

}

}
