
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datis.Data
{

using System;
    using System.Collections.Generic;
    
public partial class SerialNumber
{

    public int Id { get; set; }

    public string SerialNumber1 { get; set; }

    public Nullable<System.DateTime> InsertDate { get; set; }

    public string Name { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public Nullable<int> ProductId { get; set; }

    public string BuyDate { get; set; }

    public string Description { get; set; }

}

}
