Ext.define('prada.page.models.AHDBox', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'Id', type: 'int' },
        { name: 'Name', type: 'string' },
        { name: 'Model', type: 'string' },
        { name: 'Overview' },
        { name: 'Description' },
        { name: 'Price' },
        { name: 'ShowPrice' },

        { name: 'ImageSensor' },
        { name: 'ScanMode' },
    { name: 'NumberOfActivePixels' },
    { name: 'TotalNumberOfPixels' },
{ name: 'MinimumIllumination' },
{ name: 'SNRatio' },
{ name: 'DayNight' },
{ name: 'BackLight' },
{ name: 'AGC' },
{ name: 'WhiteBalance' },
{ name: 'NoiseReduction' },
{ name: 'EZoom' },
{ name: 'Brightness' },
    { name: 'IsNew' },
{ name: 'Mirror' },
{ name: 'PrivacyZone' },
{ name: 'Motion' },
{ name: 'OSD' },
{ name: 'ACE' },
{ name: 'LensMount' },
{ name: 'MaxIRLEDsLength' },
{ name: 'HardwareFlash' },
{ name: 'Ethernet' },
{ name: 'VideoOutput' },
{ name: 'Compression' },
{ name: 'MaxFrameRate' },
{ name: 'BitrateControl' },
{ name: 'AudioCompression' },
{ name: 'AudioInterface' },
{ name: 'Event' },
{ name: 'EventOutput' },
{ name: 'Recording' },
{ name: 'Client' },
{ name: 'NetworkProtocol' },
{ name: 'SmartFunction' },
{ name: 'WiFi' },
{ name: 'Compatibility' },
{ name: 'OperatingTemp' },
{ name: 'Weight' },
{ name: 'Dimension' },
{ name: 'PowerSupply' },
{ name: 'PowerConsumption' }]
});