Ext.define('prada.page.models.AHDPtz', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'Id', type: 'int' },
        { name: 'Name', type: 'string' },
        { name: 'Model', type: 'string' },
        { name: 'Overview' },
        { name: 'Description' },
        { name: 'Price' },
        { name: 'ShowPrice' },
        
         { name: 'ImageSensor' },
     { name: 'EffectivePixels' },
     { name: 'ScanningSystem' },
     { name: 'ElectronicShutterSpeed' },
     { name: 'MinIllumination' },
     { name: 'SNRatio' },
     { name: 'VideoOutput' },
     { name: 'DayNight' },
     { name: 'BacklightCompensation' },
     { name: 'WhiteBalance' },
     { name: 'GainControl' },
     { name: 'NoiseReduction' },
     { name: 'PrivacyMasking' },
	 { name: 'DigitalZoom' },
	 { name: 'Defog' },
	 { name: 'IR' },
     { name: 'FocalLength' },
     { name: 'MaxAperture' },
     { name: 'FocusControl' },
    { name: 'IsNew' },
     { name: 'AngleOfView' },
     { name: 'CloseFocusDistance' },
     { name: 'PanTiltRange' },
     { name: 'ManualControlSpeed' },
     { name: 'PresetSpeed' },
     { name: 'Preset' },
     { name: 'PTZMode' },
     { name: 'SpeedSetup' },
     { name: 'PowerUpAction' },
     { name: 'IdleMotion' },
     { name: 'TimeTask' },
     { name: 'PTZProtocol' },
     { name: 'VideoCompression' },
     { name: 'Resolution' },
     { name: 'FrameRate' },
     { name: 'BitRate' },
     { name: 'AudioCompression' },
     { name: 'Interface' },
     { name: 'AutoTracking' },
     { name: 'IVS' },
     { name: 'TrackingTriggerMode' },
     { name: 'TrackingTriggerEvent' },
     { name: 'Ethernet' },
     { name: 'Protocol' },
     { name: 'ONVIF' },
     { name: 'MaxUserAccess' },
     { name: 'SmartPhone' },
     { name: 'MemorySlot' },
     { name: 'Alarm' },
     { name: 'PowerSupply' },
     { name: 'PowerConsumption' },
     { name: 'WorkingEnvironment' },
     { name: 'IngressProtection' },
     { name: 'VandalResistance' },
     { name: 'Dimensions' },
     { name: 'Weight' },



    ]
});