Ext.define('prada.page.models.AnalogIrDome', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'Id', type: 'int' },
        { name: 'Name', type: 'string' },
        { name: 'Model', type: 'string' },
        { name: 'Overview' },
        { name: 'Description' },
        { name: 'Price' },
        { name: 'ShowPrice' },
        { name: 'ImageSensor' },
        { name: 'EfectivePixels' },
        { name: 'HorizontalResolution' },
        { name: 'ElectronicShutter' },
        { name: 'Synchronization' },
        { name: 'MinIllumination' },
        { name: 'SNRatio' },
        { name: 'VideoOutput' },
        { name: 'MaxIrLEDsLength' },
        { name: 'DayNight' },
        { name: 'OSD' },
        { name: 'BacklightCompensation' },
        { name: 'WhiteBalance' },
        { name: 'GainControl' },
        { name: 'NoiseReduction' },
        { name: 'PrivacyMasking' },
        { name: 'PictureAdjustment' },
        { name: 'DigitalZoom' },
    { name: 'IsNew' },
        { name: 'FocalLength' },
        { name: 'FocusType' },
        { name: 'LensType' },
        { name: 'MountType' },
        { name: 'PowerSupply' },
        { name: 'PowerConsumption' },
        { name: 'WorkingEnvironment' },
        { name: 'Dimensions' },
        { name: 'Weight' }
    ]
});