Ext.define('prada.page.models.AnalogPtz', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'Id', type: 'int' },
        { name: 'Name', type: 'string' },
        { name: 'Model', type: 'string' },
        { name: 'Overview' },
        { name: 'Description' },
        { name: 'Price' },
        { name: 'ShowPrice' },
        { name: 'ImageSensor' },
        { name: 'EfectivePixels' },
        { name: 'HorizontalResolution' },
        { name: 'ElectronicShutter' },
        { name: 'Synchronization' },
        { name: 'MinIllumination' },
        { name: 'SNRatio' },
        { name: 'VideoOutput' },
        { name: 'MaxIrLEDsLength' },
        { name: 'DayNight' },

        { name: 'BacklightCompensation' },
        { name: 'WhiteBalance' },
        { name: 'GainControl' },
        { name: 'FocalLength' },

        { name: 'ScanningSystem' },
        { name: 'ElectronicShutterSpeed' },
    { name: 'IsNew' },
        { name: 'NoiseReduction' },
        { name: 'PrivacyMasking' },
        { name: 'DigitalZoom' },
        { name: 'MaxAperture' },
        { name: 'FocusControl' },
        { name: 'AngleOfView' },
        { name: 'CloseFocusDistance' },
        { name: 'PanTiltRange' },
        { name: 'ManualControlSpeed' },
        { name: 'PresetSpeed' },
        { name: 'Preset' },
        { name: 'PTZMode' },
        { name: 'SpeedSetup' },
        { name: 'PowerUpAction' },
        { name: 'IdleMotion' },
        { name: 'TimeTask' },
        { name: 'Protocol' },
        { name: 'RS485' },
        { name: 'Alarm' },
        { name: 'IngressProtection' },


        { name: 'PowerSupply' },
        { name: 'PowerConsumption' },
        { name: 'WorkingEnvironment' },
        { name: 'Dimensions' },
        { name: 'Weight' }
    ]
});